# Generated by Django 2.1.2 on 2019-04-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_auto_20190428_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
