# Generated by Django 2.1.2 on 2019-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0009_auto_20190525_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
