# Generated by Django 2.1.2 on 2019-05-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0011_auto_20190525_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default='What is life?', null=True),
        ),
    ]
