# Generated by Django 2.1.2 on 2019-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0012_auto_20190525_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='General', max_length=42, null=True),
        ),
    ]
