# Generated by Django 2.1.2 on 2019-05-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0017_auto_20190530_1833'),
        ('blogsite', '0016_auto_20190530_1823'),
    ]

    operations = [
    ]
