# Generated by Django 2.1.2 on 2020-01-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0021_auto_20190928_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
