# Generated by Django 2.1.2 on 2020-01-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0023_auto_20200107_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='questions',
            new_name='question',
        ),
    ]
