# Generated by Django 2.1.2 on 2020-01-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0024_auto_20200107_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
