# Generated by Django 2.1.2 on 2020-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0025_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
