# Generated by Django 2.1.2 on 2021-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0026_question_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(blank=True, default=1500.0, null=True),
        ),
    ]
