# Generated by Django 2.1.2 on 2021-09-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0027_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='volatility',
            field=models.FloatField(blank=True, default=150.0, null=True),
        ),
    ]
