# Generated by Django 2.1.2 on 2021-09-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0028_profile_volatility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_contests_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
