# Generated by Django 2.1.2 on 2022-08-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0029_profile_no_of_contests_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
