# Generated by Django 2.2.28 on 2026-08-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0030_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_qotd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longest_streak',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
