# Generated by Django 2.1.2 on 2020-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200723_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=models.TextField(),
        ),
    ]
