# Generated by Django 2.1.2 on 2020-08-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200726_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='options',
            new_name='guess',
        ),
    ]
