# Generated by Django 2.1.2 on 2020-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200804_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='second_answer',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='third_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
