# Generated by Django 2.1.2 on 2021-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200901_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
