# Generated by Django 2.1.2 on 2021-09-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizquestion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='has_rating_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
