# Generated by Django 2.1.2 on 2021-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_contest_has_rating_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='guess',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='second_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='third_answer',
            field=models.TextField(blank=True),
        ),
    ]
