# Generated by Django 2.1.2 on 2021-09-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210903_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='level',
            field=models.IntegerField(blank=True, default=1500, null=True),
        ),
    ]
