# Generated by Django 2.1.2 on 2021-12-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinghistory',
            name='rating_before_contest',
            field=models.FloatField(blank=True, default=1500, null=True),
        ),
    ]
