# Generated by Django 2.1.2 on 2022-06-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_ratinghistory_rating_before_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
