# Generated by Django 2.2.28 on 2026-08-27 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0014_quizquestion_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='images/')),
                ('image_url', models.URLField(blank=True)),
                ('answer', models.TextField()),
                ('second_answer', models.TextField(blank=True)),
                ('third_answer', models.TextField(blank=True)),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QOTDSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('qotd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionOfTheDay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'qotd')},
            },
        ),
    ]
