# Generated by Django 2.2.28 on 2026-09-01 08:17

from django.db import migrations, models


def backfill_name_from_genre(apps, schema_editor):

    # Existing contests predate the "name" field - give them a sensible
    # default so they don't show up blank in the UI.
    Contest = apps.get_model('quiz', 'Contest')

    for contest in Contest.objects.filter(name=''):
        contest.name = contest.genre
        contest.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_qotdsubmission_questionoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(backfill_name_from_genre, migrations.RunPython.noop),
    ]
