"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get_env(name, default=None):
    """Read a setting from the environment.

    Raises a clear error at startup if a required secret (no default) is
    missing, instead of silently falling back to a hardcoded value.
    """
    value = os.environ.get(name, default)
    if value is None:
        raise RuntimeError(
            "Missing required environment variable: {}".format(name)
        )
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['127.0.0.1', 'algorithmist.pythonanywhere.com', 'qnondrum.pythonanywhere.com', 'www.putfunda.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphos',
    'blogsite',
    'blogposts',
    'captcha',
    'quiz',
    'ckeditor'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Database backend is selected via DB_ENGINE:
#   'sqlite'  -> local file database, no server needed (good for local dev)
#   'mysql'   -> the production MySQL configuration (the default)
DB_ENGINE = os.environ.get('DB_ENGINE', 'mysql').lower()

if DB_ENGINE == 'sqlite':

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': get_env('DB_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
        }
    }

else:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': get_env('DB_NAME', 'qnondrum$default'),
            'USER': get_env('DB_USER', 'qnondrum'),
            'PASSWORD': get_env('DB_PASSWORD'),
            'HOST': get_env('DB_HOST', 'qnondrum.mysql.pythonanywhere-services.com'),
            'PORT': int(get_env('DB_PORT', '3306')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

"""
# Add these new lines
"""
#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)


# For serving files uploaded by user (development)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Login variables

LOGIN_URL = 'login'

# Support for CKEditor

CKEDITOR_CONFIGS = {'default' : {'height' : 600, 'width' : 400} }

# Setting for session expiry

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

EMAIL_USE_TLS = True
EMAIL_HOST = get_env('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_HOST_USER = get_env('EMAIL_HOST_USER', 'putfundaofficial@gmail.com')
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD')
EMAIL_PORT = int(get_env('EMAIL_PORT', '587'))

# Properties for re-captcha
RECAPTCHA_PRIVATE_KEY = get_env('RECAPTCHA_PRIVATE_KEY')
RECAPTCHA_PUBLIC_KEY = get_env('RECAPTCHA_PUBLIC_KEY')