# Generated by Django 2.1.2 on 2020-04-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0002_auto_20200319_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anon',
            field=models.BooleanField(default=False),
        ),
    ]
