# Generated by Django 2.1.2 on 2020-04-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0003_post_anon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anon',
        ),
    ]
