# Generated by Django 2.1.2 on 2020-04-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0004_remove_post_anon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anon',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
