# Generated by Django 2.1.2 on 2020-09-29 05:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0005_post_anon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default='Life is good.'),
        ),
    ]
