# Generated by Django 2.1.2 on 2020-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_auto_20200929_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
